Backend/src/Bolt.Web/Controllers/MenuController.cs
namespace Bolt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Bolt.DTOs.Orders;
    using Bolt.DTOs.Products;
    using Bolt.Services.Interfaces;
    using Bolt.Web.Services;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;

    [Authorize]
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly ICookieCachingService _cacheService;

        public MenuController(
            IMenuService menuService,
            ICookieCachingService cacheService)
        {
            this._menuService = menuService;
            this._cacheService = cacheService;
        }

        public async Task<IActionResult> Index()
        {
            GetMenuDTO menu = await this._menuService.GetMenuAsync();

            return this.View(menu);
        }

        [HttpPost]
        public void AddItemToCart(int productId, string productName, int quantity)
        {
            string productsCache = this._cacheService.Get("products");

            if (productsCache == null)
            {
                var products = new List<ProductShoppingCartCache>
                {
                    new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    }
                };

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
            else
            {
                var products = JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(productsCache);

                if (products.Any(p => p.Id == productId))
                {
                    products.First(p => p.Id == productId).Quantity += quantity;
                }
                else
                {
                    var productsInShoppingCart = new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    };
                    products.Add(productsInShoppingCart);
                }

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
        }

        [HttpGet]
        public IActionResult OpenProductDetailsAsync(int productId)
        {
            return this.RedirectToAction("Index", "ProductDetailsController", new {productId});
        }
    }
}

Backend/src/Bolt.Web/Controllers/OrdersController.cs
namespace Bolt.Web.Controllers
{
    using System.Threading.Tasks;
    using Bolt.Services.Interfaces;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersService;

        public OrdersController(IOrdersService ordersService)
        {
            this._ordersService = ordersService;
        }

        public async Task<IActionResult> ReOrder(int orderId)
        {
            int newOrderId = await this._ordersService.ReOrder(orderId);

            return this.RedirectToAction("Index", "OrderTracker", new {orderId = newOrderId});
        }
    }
}

Backend/src/Bolt.Web/Controllers/UserSettingsController.cs
namespace Bolt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Bolt.DTOs.Orders;
    using Bolt.DTOs.Users;
    using Bolt.Services.Interfaces;
    using Bolt.Web.ViewModels.UserSettings;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class UserSettingsController : Controller
    {
        private readonly IUsersService _usersService;
        private readonly IOrdersService _ordersService;

        public UserSettingsController(IUsersService usersService, IOrdersService ordersService)
        {
            this._usersService = usersService;
            this._ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            const int numberOfOrdersToTake = 10;
            string username = this.User.Identity.Name;

            UserDTO user = await this._usersService.GetUserByUsernameAsync(username);
            List<GetOrderDTO> orders = await this._ordersService.GetOrdersForUsername(username, numberOfOrdersToTake);

            var userSettingsViewModel = new UserSettingsViewModel(user, orders);
            return this.View(userSettingsViewModel);
        }

        public async Task<IActionResult> Edit(UserDTO model)
        {
            string username = this.User.Identity.Name;
            await this._usersService.EditUserAsync(username, model);

            return this.RedirectToAction("Index");
        }
    }
}

Backend/src/Bolt.Web/Views/UserSettings/Details.cshtml
@model UserDTO

<h2>Details</h2>

<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Backend/src/Bolt.Web/Views/UserSettings/Edit.cshtml
@model UserDTO

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ApplicationUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Town" class="control-label"></label>
                <input asp-for="Town" class="form-control" />
                <span asp-validation-for="Town" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend/src/Bolt.Web/Views/UserSettings/Index.cshtml
@using Bolt.Web.ViewModels.UserSettings
@model UserSettingsViewModel
@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-30">
    <div class="row">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#about-me">About Me</a></li>
            <li><a data-toggle="tab" href="#orders">Orders</a></li>
        </ul>

        <div class="tab-content">
            <div id="about-me" class="tab-pane fade in active">
                <hr />
                @Html.Partial("_AboutMe", Model.User)
                <hr />
            </div>
            <div id="orders" class="tab-pane fade">
                <hr />
                @Html.Partial("_Orders", Model.Orders)
                <hr />
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend/src/Bolt.Web/Views/UserSettings/_AboutMe.cshtml
@model UserDTO

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Town" class="control-label"></label>
                <input asp-for="Town" class="form-control" />
                <span asp-validation-for="Town" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

Backend/src/Bolt.Web/Views/UserSettings/_Orders.cshtml
@model List<GetOrderDTO>

@if (Model == null || !Model.Any())
{
    <div class="alert alert-info" id="no-items-message">
        Currently you haven't ordered anything <strong>@Html.ActionLink("Order", "Index", "Menu", null, null)</strong>
    </div>
}
else
{

    <div class="container">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Order Placed Time</th>
                    <th>Order Lines</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (GetOrderDTO order in Model)
                {
                    <tr>
                        <td>@order.CreatedOn</td>
                        <td>
                            @if (order.OrderLines.Any())
                            {
                                OrderLine lastItem = order.OrderLines.Last();
                                foreach (OrderLine orderLine in order.OrderLines)
                                {
                                    if (lastItem == orderLine)
                                    {
                                        <span><strong>@orderLine?.Quantity</strong>x @orderLine?.ProductName </span>
                                    }
                                    else
                                    {
                                        <span><strong>@orderLine?.Quantity</strong>x @orderLine?.ProductName &loz; </span>
                                    }
                                }
                            }
                        </td>
                        <td>@Html.ActionLink("Order", "ReOrder", "Orders", new { orderId = order.Id }, new { @class = "btn btn-success" })</td>
                    </tr>
                }
            </tbody>
        </table>


        @*<div class="row">
                <div class="col-md-3">@order.CreatedOn</div>
                <div class="col-md-3"></div>
                <div class="col-md-3">Actions</div>
            </div>
            @foreach (GetOrderDTO order in Model)
            {
                <div class="row">
                    <div class="col-md-3">@order.CreatedOn</div>
                    <div class="col-md-3">
                        @if (order.OrderLines.Any())
                        {
                            foreach (OrderLine orderLine in order.OrderLines)
                            {
                                <span><strong>@orderLine?.Quantity</strong>x @orderLine?.ProductName | </span>
                            }
                        }
                    </div>
                    <div class="col-md-3">@Html.ActionLink("Order", "ReOrder", "Orders", new { orderId = order.Id }, new { @class = "btn btn-success" })</div>
                </div>
            }*@
    </div>
}