Backend/src/Bolt.Web/Controllers/CartController.cs
namespace Bolt.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Bolt.DTOs.Orders;
    using Bolt.DTOs.Products;
    using Bolt.Models;
    using Bolt.Services.Interfaces;
    using Bolt.Web.Services;
    using Bolt.Web.ViewModels.Cart;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;

    [Authorize]
    public class CartController : Controller
    {
        private readonly ICookieCachingService _cookieCachingService;
        private readonly IProductsService _productService;
        private readonly IOrdersService _ordersService;
        private readonly IUsersService _usersService;

        public CartController(
            ICookieCachingService cookieCachingService,
            IProductsService productService,
            IOrdersService ordersService,
            IUsersService usersService)
        {
            this._cookieCachingService = cookieCachingService;
            this._productService = productService;
            this._ordersService = ordersService;
            this._usersService = usersService;
        }

        public async Task<IActionResult> Index()
        {
            var products = new List<ProductViewModel>();

            string cachedProducts = this._cookieCachingService.Get("products");

            if (string.IsNullOrEmpty(cachedProducts))
            {
                return this.View(products);
            }

            var deserializedProducts =
                JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(cachedProducts);

            IEnumerable<int> productIds = deserializedProducts.Select(a => a.Id);
            List<ProductDTO> productEntities = await this._productService.GetProductsByIDsAsync(productIds);

            foreach (ProductDTO productDTO in productEntities)
            {
                products.Add(new ProductViewModel
                {
                    Id = productDTO.Id,
                    Name = productDTO.Name,
                    Price = productDTO.Price,
                    Description = productDTO.Description,
                    Quantity = deserializedProducts.FirstOrDefault(p => p.Id == productDTO.Id)?.Quantity
                });
            }

            return this.View(products);
        }

        [HttpDelete]
        public bool RemoveItem(int? productId)
        {
            string cachedProducts = this._cookieCachingService.Get("products");

            var deserializedProducts = JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(cachedProducts);

            deserializedProducts.RemoveAll(pr => pr.Id == productId);

            this._cookieCachingService.Set("products", JsonConvert.SerializeObject(deserializedProducts), 30);

            return true;
        }

        [HttpPost]
        public void EditItemQuantity(int productId, int quantity)
        {
            string cachedProducts = this._cookieCachingService.Get("products");

            var deserializedProducts = JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(cachedProducts);

            ProductShoppingCartCache product = deserializedProducts.FirstOrDefault(p => p.Id == productId);
            product.Quantity = quantity;

            this._cookieCachingService.Set("products", JsonConvert.SerializeObject(deserializedProducts), 30);
        }

        public async Task<IActionResult> Order()
        {
            string cachedProducts = this._cookieCachingService.Get("products");

            var deserializedProducts =
                JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(cachedProducts);

            string username = this.User.Identity.Name;
            string userId = await this._usersService.GetUserIdByUsernameAsync(username);

            var orderDTO = new CreateOrderDTO
            {
                CreatedOn = DateTime.Now,
                OrderStatus = OrderStatus.Accepted,
                UserId = userId,
                Products = deserializedProducts
            };

            int orderId = await this._ordersService.AddOrderAsync(orderDTO);

            this._cookieCachingService.Remove("products");

            return this.RedirectToAction("Index", "OrderTracker", new {orderId});
        }
    }
}

Backend/src/Bolt.Web/Controllers/IdentityController.cs
namespace Bolt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Bolt.DTOs.Users;
    using Bolt.Services.Interfaces;
    using Bolt.Web.Infrastructure.Statics;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRole)]
    public class IdentityController : Controller
    {
        private readonly IUsersService _usersService;

        public IdentityController(IUsersService usersService)
        {
            this._usersService = usersService;
        }

        public async Task<IActionResult> All()
        {
            List<ListUserViewModel> users = await this._usersService.GetAllUsersAsync();

            return this.View(users);
        }
    }
}

Backend/src/Bolt.Web/Controllers/MenuController.cs
namespace Bolt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Bolt.DTOs.Orders;
    using Bolt.DTOs.Products;
    using Bolt.Services.Interfaces;
    using Bolt.Web.Services;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;

    [Authorize]
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly ICookieCachingService _cacheService;

        public MenuController(
            IMenuService menuService,
            ICookieCachingService cacheService)
        {
            this._menuService = menuService;
            this._cacheService = cacheService;
        }

        public async Task<IActionResult> Index()
        {
            GetMenuDTO menu = await this._menuService.GetMenuAsync();

            return this.View(menu);
        }

        [HttpPost]
        public void AddItemToCart(int productId, string productName, int quantity)
        {
            string productsCache = this._cacheService.Get("products");

            if (productsCache == null)
            {
                var products = new List<ProductShoppingCartCache>
                {
                    new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    }
                };

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
            else
            {
                var products = JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(productsCache);

                if (products.Any(p => p.Id == productId))
                {
                    products.First(p => p.Id == productId).Quantity += quantity;
                }
                else
                {
                    var productsInShoppingCart = new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    };
                    products.Add(productsInShoppingCart);
                }

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
        }

        [HttpGet]
        public IActionResult OpenProductDetailsAsync(int productId)
        {
            return this.RedirectToAction("Index", "ProductDetailsController", new {productId});
        }
    }
}

Backend/src/Bolt.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Bolt - OnlineOrderManager</title>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <link href="template/img/favicon.png" rel="icon" type="image/png">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="~/template/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/template/theme/css/theme.css" rel="stylesheet" />

</head>
<body>
    <header class="header header-fixed nav-down">
        <div class="box mb-0">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a asp-area="" asp-controller="Identity" asp-action="All" class="header-logo-small">
                                <img src="~/template/img/logo - 1.png" alt="store logo">
                            </a>
                            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse js-navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="header-link"><a asp-area="" asp-controller="Identity" asp-action="All">Home</a></li>
                                @if (this.User.Identity.IsAuthenticated)
                                {
                                    <li class="header-link"><a asp-area="" asp-controller="Menu" asp-action="Index">Menu</a></li>
                                    <li class="header-link"><a asp-area="" asp-controller="Cart" asp-action="Index">Cart</a></li>
                                }
                            </ul>
                            @await Html.PartialAsync("_LoginPartial")
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </header>



    @RenderBody()
    <footer class="light-bg ">
        <div class="footer pt-60 pb-60" id="footer">
            <div class="container">
                <div class="row">
                    <div class="smartphone-fw col-sm-3">
                        <h6 class="heading mt-0"><span>//</span> CONTACT </h6>
                        <address>
                            <strong>Bolt Coffee Store</strong><br>
                            Sofia, 1000<br>
                            +359895767201
                        </address>

                    </div>
                    @*<div class="col-xs-12 col-sm-6 col-md-3">
                        <h6 class="heading mt-0"><span>//</span> STAY IN TOUCH</h6>
                        <form>
                            <fieldset>
                                <div class="form-group">
                                    <div class="footer-newsletter">
                                        <input class="form-control" id="firstName" placeholder="First name" type="text">
                                        <button class="btn btn-link" type="button"><span class="ti-plus"></span></button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                        <ul class="footer-social" data-wow-delay="0.6s">
                            <li><a href="#" class="pull-left"><span class="ti-facebook"></span></a></li>
                            <li><a href="#" class="pull-left"><span class="ti-twitter"></span></a></li>
                            <li><a href="#" class="pull-left"><span class="ti-instagram"></span></a></li>
                            <li><a href="#" class="pull-left"><span class="ti-youtube"></span></a></li>
                        </ul>
                    </div>*@
                </div>
            </div>
        </div>

        <div class="footer-bottom">
            <div class="container">
                <p class="pull-left"> Copyright © Laurent 2017. All right reserved. </p>
            </div>
        </div>
    </footer>

    <script src="~/template/js/jquery-1.11.2.min.js"></script>
    <script src="~/template/js/wow.js"></script>
    @*<script>
            window.jQuery || document.write('<script src="~/template/js/jquery-1.11.2.min.js"><\/script>')
        </script>*@
    <script src="~/template/js/swiper.min.js"></script>
    <script src="~/template/js/bootstrap.min.js"></script>
    <script src="~/template/js/jquery.countTo.js"></script>
    <script src="~/template/js/jquery.inview.js"></script>
    <script src="~/template/js/jquery.countdown.js"></script>
    <script src="~/template/js/jquery.vide.js"></script>
    <script src="~/template/js/main.js"></script>
@RenderSection("Scripts", false)
</body>
</html>






@*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Menu" asp-action="All" class="navbar-brand">Bolt</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Bolt</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", false)
    </body>
    </html>*@