Backend/src/Bolt.Web/Models/Menu/ProductShoppingCartCache.cs
namespace Bolt.Web.Models.Menu
{
    public class ProductShoppingCartCache
    {
        public int Id { get; set; }

        public int Quantity { get; set; }
    }
}

Backend/src/Bolt.Web/Controllers/MenuController.cs
namespace Bolt.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Bolt.DTOs.Orders;
    using Bolt.DTOs.Products;
    using Bolt.Services.Interfaces;
    using Bolt.Web.Services;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;

    [Authorize]
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly ICookieCachingService _cacheService;

        public MenuController(
            IMenuService menuService,
            ICookieCachingService cacheService)
        {
            this._menuService = menuService;
            this._cacheService = cacheService;
        }

        public async Task<IActionResult> Index()
        {
            GetMenuDTO menu = await this._menuService.GetMenuAsync();

            return this.View(menu);
        }

        [HttpPost]
        public void AddItemToCart(int productId, string productName, int quantity)
        {
            string productsCache = this._cacheService.Get("products");

            if (productsCache == null)
            {
                var products = new List<ProductShoppingCartCache>
                {
                    new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    }
                };

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
            else
            {
                var products = JsonConvert.DeserializeObject<List<ProductShoppingCartCache>>(productsCache);

                if (products.Any(p => p.Id == productId))
                {
                    products.First(p => p.Id == productId).Quantity += quantity;
                }
                else
                {
                    var productsInShoppingCart = new ProductShoppingCartCache
                    {
                        Id = productId,
                        Quantity = quantity,
                        ProductName = productName
                    };
                    products.Add(productsInShoppingCart);
                }

                this._cacheService.Set("products", JsonConvert.SerializeObject(products), 30);
            }
        }

        [HttpGet]
        public IActionResult OpenProductDetailsAsync(int productId)
        {
            return this.RedirectToAction("Index", "ProductDetailsController", new {productId});
        }
    }
}

Backend/src/Bolt.Web/Controllers/ProductDetailsController.cs
namespace Bolt.Web.Controllers
{
    using System.Threading.Tasks;
    using Bolt.DTOs.Products;
    using Bolt.Services.Interfaces;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class ProductDetailsController : Controller
    {
        private readonly IProductsService _productsService;

        public ProductDetailsController(IProductsService productsService)
        {
            this._productsService = productsService;
        }

        public async Task<IActionResult> Index(int productId)
        {
            ProductDetailsDTO product = await this._productsService.GetProductDetailsAsync(productId);
            return this.View(product);
        }
    }
}

Backend/src/Bolt.Web/Views/Menu/Index.cshtml
@model GetMenuDTO
<script src="~/lib/jquery/dist/jquery.js"></script>

<div class="container mt-30">
    <div class="row">
        <div class="col-md-12 mb-30">
            <ol class="breadcrumb mb-0">
                <li class="active">All products</li>
            </ol>
        </div>
        <div class="col-md-12">
            <div class="row">

                @if (Model != null)
                {
                    foreach (Product product in Model.Products)
                    {
                        <div class="smartphone-fw col-md-4 wow fadeIn" data-wow-delay="0.2s">
                            <div class="product-box  product-box-vertical">
                                <div class="product-box-wrapper no-padding product-box-wrapper no-padding-bg">
                                    <div class="product-box-image">
                                        <img class="img-responsive" src="~/template/img/products/coffee 2716_1810.jpg" alt="product image">
                                        <span class="product-box-hover-content zoom">
                                            <span class="product-box-hover-content-container">
                                                <span class="product-box-hover-content-icons">
                                                    <a href="/ProductDetails?productId=@product.Id" title="details">
                                                        <span class="ti-layout-list-thumb"></span>
                                                    </a>
                                                </span>
                                            </span>
                                        </span>
                                    </div>
                                    <div class="product-box-details">
                                        <span class="product-box-new">new!</span>
                                        <h5>@product.Name</h5>
                                        <div class="product-box-rating">
                                            <ul>
                                                <li><span class="glyphicon glyphicon-star"></span></li>
                                                <li><span class="glyphicon glyphicon-star"></span></li>
                                                <li><span class="glyphicon glyphicon-star"></span></li>
                                                <li><span class="glyphicon glyphicon-star"></span></li>
                                                <li><span class="glyphicon glyphicon-star-empty unactive"></span></li>
                                            </ul>
                                        </div>
                                        <span class="product-box-price h5">$ @product.Price</span>
                                        <a product-id="@product.Id" product-name="@product.Name" class="add-to-cart-button btn btn-link btn-sm no-padding add-item" data-image="~/template/img/products/product-01.jpg" data-name="@product?.Name" data-cost="@product.Price" data-id="1">
                                            add to cart
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>


@*<div class="container">
        <div class="row">
            @if (Model != null)
            {
                foreach (Product product in Model.Products)
                {
                    <div class="col-md-4">
                        Product Name: @product?.Name <br />
                        Product Description: @product?.Description <br />
                        Product Price: @product.Price <br />

                        <input type="number" value="1" id="product-quantity-@product.Id" min="1" /><br />
                        <input type="button" value="Add to cart" product-id="@product.Id" product-name="@product.Name" class="btn btn-primary add-to-cart-button" /><br />

                        @Html.ActionLink("Details", "All", "ProductDetails", new { productId = product.Id }, new { @class = "btn btn-primary" })
                    </div>
                }
            }
        </div>
    </div>*@
<script>
    $(document).ready(function() {
        $('.add-to-cart-button').click(function () {
            const productId = parseInt($(this).attr('product-id'));
            const productName = $(this).attr('product-name').toString();
            const quantity = 1;


            $.ajax({
                type: "POST",
                url: '@Url.Action("AddItemToCart", "Menu")',
                data: { productId: productId, productName: productName, quantity: quantity },
                success: function () {
                    alert('Added item to cart');
                    //$("#product-quantity-" + productId).val(1);
                },
                error: function () {
                    //$("#product-quantity-" + productId).val(1);
                    alert('A error');
                }
            });
        });
    });
</script>